{% set name = "dwave-inspector" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-inspector-{{ version }}.tar.gz
  sha256: a03af28656a48dfc1e1ccf90d10b9d192acd462f71e7613324520c83ae76d45f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - importlib-metadata >=4.8
    - dimod >=0.10.0
    - dwave-cloud-client >=0.8.3
    - dwave-system >=1.3.0
    - flask >=2.2
    - importlib-resources >=3.2.0
    - python >=3.7
    - numpy
  run_constrained:
    - dwave-inspectorapp ==0.3.1

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-inspector
  summary: D-Wave Problem Inspector tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
