{% set name = "dwave-inspector" %}
{% set version = "0.5.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-inspector-{{ version }}.tar.gz
  sha256: c36bbc5cc7cb01f0f8168d7e4770f4e28fd468b1c90fc3d1e7c6e7d1ea7c4838

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - orjson >=3.10.0
    - importlib-metadata >=4.8
    - dimod >=0.10.0
    - dwave-cloud-client >=0.11.0,<0.13.0
    - dwave-system >=1.3.0
    - flask >=2.2,<4
    - importlib-resources >=3.2.0
    - python >=3.7
    - numpy
  run_constrained:
    - dwave-inspectorapp ==0.3.1

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-inspector
  summary: D-Wave Problem Inspector tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
