{% set name = "dwave-inspector" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-inspector-{{ version }}.tar.gz
  sha256: 6012ee4c75308212d4c0006a414b5fcebd2de752397f2c7a85581e18140ca318

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dimod >=0.8.17
    - dwave-cloud-client >=0.8.3
    - dwave-system >=1.3.0
    - flask >=1.1.1
    - importlib-resources >=3.2.0
    - python >=3.6
    - numpy
  run_constrained:
    - dwave-inspectorapp ==0.2.4

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-inspector
  summary: D-Wave Problem Inspector tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
