{% set name = "dwave-inspector" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-inspector-{{ version }}.tar.gz
  sha256: e455642e4d6b059afdc2365dd740882fb17dbd769a260b49b50fcbcf7bdff5b6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - dimod >=0.8.17
    - dwave-cloud-client >=0.8.3
    - dwave-system >=1.3.0
    - flask >=1.1.1
    - importlib-resources >=3.2.0
    - python
    - numpy
  run_constrained:
    - dwave-inspectorapp ==0.2.4

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-inspector
  summary: D-Wave Problem Inspector tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
